### ISSUE TITLE
Why IHost?

### ISSUE THREAD

**Issue by duongphuhiep** [parko65/AvaloniaHostingDI#1]
Hello, I'm not sure if I mis-understand something

The `AppHost.Run()` is not called anywhere. It was always Avalonia which manage the application lifecycle, not the `IHost` we created.

So what is the point of creating this IHost? 

If it serves only for DI, then isn't it better to replace this IHost with a  more appropriated interface `IServiceProvider`?

**Comment by parko65** [comment]
This is purely a trimmed down example taken from a WinUI3 app I have.

You are correct that if you want to just manage dependencies then go with the IServiceProvider approach. At the time this was posted there was hardly any documentation of what the best practice was to implement DI in an Avalonia app.

This implementation is commonly used in Desktop apps and follows best practices. Using the IHost enables me to easily read config files, run background services using IHostedService.

Just to appease I've added AppHost.Start() method.

**Comment by duongphuhiep** [comment]
Thanks for the clarification, I discovered your repository while looking for a good Avalonia's DI guides. 

The official documentation is not helpful at all: https://github.com/AvaloniaUI/avalonia-docs/issues/525

**Comment by parko65** [comment]
> Thanks for the clarification, I discovered your repository while looking for a good Avalonia's DI guides.
> 
> The official documentation is not helpful at all: [AvaloniaUI/avalonia-docs#525](https://github.com/AvaloniaUI/avalonia-docs/issues/525)

No, thank you for taking the time to investigate this repo and giving your thoughts.
